title: ajaypanyala.github.io
description: Home Page
google_analytics: 
remote_theme             : "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin    : "contrast"

github_username: ajaypanyala

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
