title: ajaypanyala.github.io
description: Home Page
google_analytics: 
remote_theme             : "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin    : "contrast"

github_username: ajaypanyala

include: ["_pages"]

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

include:
  - _pages

# Defaults
defaults:

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      author_profile: false  
